# -*- coding: utf-8 -*-
"""data_preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-iLWUuvuNIJCPAMrjBlBeqOUtTcdTNw
"""

import pandas as pd
import numpy as np
from scipy import stats

df = pd.read_csv('global_consumer_data_50k.csv')

# 1. Outlier Treatment (Z-Score)
df['AOV_ZScore'] = np.abs(stats.zscore(df['Average_Order_Value']))
df = df[df['AOV_ZScore'] < 3].drop(columns=['AOV_ZScore'])

# 2. RFM & Feature Engineering
df['Customer_LTV'] = df['Purchase_Frequency'] * df['Average_Order_Value']
df['Log_Total_Spend'] = np.log1p(df['Total_Spend'])

# 3. Categorical Encoding
df = pd.get_dummies(df, columns=['Country', 'Membership_Level'], drop_first=True)

df.to_csv('processed_global_data.csv', index=False)
print("Preprocessing Complete.")